% for all datasets (movies), check the length of NC14.
% This is for setting the reasonable limit to the decay regime calculation.
% If we have most of the movies up to 40 minutes or longer, we can safely
% say that that's the limit.

%% Load all datasets
DataTypes = {'r0-new','r1-new','r2-new','r3-new','r1-close','r1-mid','r2_1+2','r2_1+3',...
                    'r0_RuntNull','r1_RuntNull','r2_RuntNull','r3_RuntNull',...
                    'r1_close_RuntNull','r1_mid_RuntNull','r2_close_RuntNull','r2_far_RuntNull'};

%% Load the compiledData

DropboxFolder = 'S:/YangJoon/Dropbox/OpposingGradient';
% FigureRoot = 'S:/YangJoon/Dropbox/OpposingGradientsFigures/PipelineOutput';

% load data structure
load([DropboxFolder,filesep,'compiledData.mat'])

% initialize
nc14_length = nan(16,6); % DataTytpe, embryo
for i=2:length(compiledData)
    LoadedMS2Sets = compiledData{i,2};% data generated by LoadMS2Sets
    for j=1:length(LoadedMS2Sets)
        nc14 = LoadedMS2Sets(j).nc14;
        Time = LoadedMS2Sets(j).ElapsedTime;
        nc14_length(i-1,j) = Time(end) - Time(nc14);
    end
end

%% Check the minimum and maximu, distribution

hist(nc14_length(1:8,:), 5)
