function main02_08_plot_InitialSlopes_AllConstructs
%% Description 
% Compiling and avearging initial slopes from multiple embryos
% Generate plots, and also save the fields that are calculated.

%This code is using the "mean fits" files generated by my version of FitMeanAPAsymetric 
%to plot the initial rates along APaxis. 
%The T_on (time of activation of the transcription,extrapolated from the initial rate)
%can also be plotted.

%% Load the datasets (using LoadMS2Sets.m)
% New datasets with known sex
% Note that I used old datasets for the r0, for nc14, thus MeanFits.mat,
% not MeanFitsV2.mat

Data_r0 = LoadMS2Sets('r0','dontCompare')
Data_r1 = LoadMS2Sets('r1-new','dontCompare')
Data_r2 = LoadMS2Sets('r2-new','dontCompare')
Data_r3 = LoadMS2Sets('r0-new','dontCompare')

% Variants
% r1 variants
Data_r1_close = LoadMS2Sets('r1-close','dontCompare')
Data_r1_mid = LoadMS2Sets('r1-mid','dontCompare')
% r2 variants
Data_r2_close = LoadMS2Sets('r2_1+2','dontCompare')
Data_r2_far = LoadMS2Sets('r2_1+3','dontCompare')


%% Extract the fitted values from all of my datasets
% Caveat : For now (7/11/2019), I'll use r0 from my old construct since I
% don't have NC14 from the new r0 construct. Thus, I'll use MeanFits.mat
% from old r0, and MeanFitsV2 (Asymmetric fit) from the new ones.
[fittedRate_r0,fittedRateSD_r0,fittedTon_r0] = Extract_Fields_MeanFits(Data_r0,'Asymmetric');

[fittedRate_r1_female,fittedRateSD_r1_female,fittedTon_r1_female] = Extract_Fields_MeanFits(Data_r1_female,'Asymmetric');
[fittedRate_r2_female,fittedRateSD_r2_female,fittedTon_r2_female] = Extract_Fields_MeanFits(Data_r2_female,'Asymmetric');
[fittedRate_r3_female,fittedRateSD_r3_female,fittedTon_r3_female] = Extract_Fields_MeanFits(Data_r3_female,'Asymmetric');

% [fittedRate_r1_male,fittedRateSD_r1_male,fittedTon_r1_male] = Extract_Fields_MeanFits(Data_r1_male,'Asymmetric');
% [fittedRate_r2_male,fittedRateSD_r2_male,fittedTon_r2_male] = Extract_Fields_MeanFits(Data_r2_male,'Asymmetric');
% [fittedRate_r3_male,fittedRateSD_r3_male,fittedTon_r3_male] = Extract_Fields_MeanFits(Data_r3_male,'Asymmetric');
% [fittedRate_r3_prime,fittedRateSD_r3_prime,fittedTon_r3_prime] = Extract_Fields_MeanFits(Data_r3_female_prime);

%% plot individual fitted curves to check
NC = 2; %NC13
hold on
for i=1:length(Data_r0)
    errorbar(0:0.025:1,fittedRate_r0(:,NC,i),fittedRateSD_r0(:,NC,i))
end

hold on
for i=1:length(Data_r1_female)
    errorbar(0:0.025:1,fittedRate_r1(:,NC,i),fittedRateSD_r1(:,NC,i))
end

hold on
for i=1:length(Data_r2_female)
    errorbar(0:0.025:1,fittedRate_r2(:,NC,i),fittedRateSD_r2(:,NC,i))
    pause
end

hold on
for i=1:length(Data_r3_female)
    errorbar(0:0.025:1,fittedRate_r3(:,NC,i),fittedRateSD_r3(:,NC,i))
    %pause
end

hold on
for i=1:length(Data_r3_female_prime)
    errorbar(0:0.025:1,fittedRate_r3_prime(:,NC,i),fittedRateSD_r3_prime(:,NC,i))
    %pause
end

%% Calculate the average using nanmean, nanstd
average_fittedRate_r0 = nanmean(fittedRate_r0,3);
SEM_fittedRate_r0 = nanstd(fittedRate_r0,0,3)/sqrt(length(Data_r0));

average_fittedRate_r1_female = nanmean(fittedRate_r1_female,3);
SEM_fittedRate_r1_female = nanstd(fittedRate_r1_female,0,3)/sqrt(length(Data_r1_female));

average_fittedRate_r2_female = nanmean(fittedRate_r2_female,3);
SEM_fittedRate_r2_female = nanstd(fittedRate_r2_female,0,3)/sqrt(length(Data_r2_female));

average_fittedRate_r3_female = nanmean(fittedRate_r3_female,3);
SEM_fittedRate_r3_female = nanstd(fittedRate_r3_female,0,3)/sqrt(length(Data_r3_female));

% average_fittedRate_r1_male = nanmean(fittedRate_r1_male,3);
% SEM_fittedRate_r1_male = nanstd(fittedRate_r1_male,0,3)/sqrt(length(Data_r1_male));
% 
% average_fittedRate_r2_male = nanmean(fittedRate_r2_male,3);
% SEM_fittedRate_r2_male = nanstd(fittedRate_r2_male,0,3)/sqrt(length(Data_r2_male));
% 
% average_fittedRate_r3_male = nanmean(fittedRate_r3_male,3);
% SEM_fittedRate_r3_male = nanstd(fittedRate_r3_male,0,3)/sqrt(length(Data_r3_male));
% average_fittedRate_r3_prime = nanmean(fittedRate_r3_prime,3);
% SEM_fittedRate_r3_prime = nanstd(fittedRate_r3_prime,0,3)/sqrt(length(Data_r3_female_prime));


%% Color definition
% This is defining the line color
colorDict = struct();
colorDict.blue = [115,143,193]/255; %[115,143,170]/255;
colorDict.red =  [213,108,85]/255; %[200,108,85]/255;
colorDict.yellow = [234,194,100]/255;
colorDict.cyan = [108,188,233]/255;
colorDict.magenta = [208,109,171]/255;
colorDict.lightBlue = [115,142,193]/255;
colorDict.purple = [171,133,172]/255;
colorDict.green =  [122,169,116]/255; %[122,150,116]/255;
colorDict.brown = [179,155,142]/255;
colorDict.darkgreen = [126,157,144]/255;

ColorChoice = [colorDict.magenta; colorDict.lightBlue; colorDict.yellow; colorDict.red; colorDict.brown]; % 4 embryos max. it could be extended easily
%% Plot the averaged fittedRate (initial rate of RNAP loading), and SEM

FigPath = 'E:\YangJoon\LivemRNA\Data\Dropbox\Garcia Lab\Figures\Opposing Gradients\Data\InitialSlope_Asymmetric\';

% % NC12
% InitialRate_NC12_figure = figure;
% nc = 1; % NC12
% hold on
% errorbar(0:0.025:1,average_fittedRate_r0(:,nc),SEM_fittedRate_r0(:,nc))
% errorbar(0:0.025:1,average_fittedRate_r1(:,nc),SEM_fittedRate_r1(:,nc))
% errorbar(0:0.025:1,average_fittedRate_r2(:,nc),SEM_fittedRate_r2(:,nc))
% errorbar(0:0.025:1,average_fittedRate_r3(:,nc),SEM_fittedRate_r3(:,nc))
%errorbar(0:0.025:1,average_fittedRate_r3_prime(:,nc),SEM_fittedRate_r3_prime(:,nc))

% legend('r0','r1','r2','r3')
% xlabel('AP Position')
% ylabel('Initial rate (AU/min)')
% title('Initial rate of RNAP loading along AP axis, at NC 14')
% StandardFigure(InitialRate_NC12_figure, InitialRate_NC12_figure.CurrentAxes)
% 
% saveas(InitialRate_NC12_figure,[FigPath 'InitialRate_AsymmetricFit_r0123' , '_NC12' , '.pdf']); 

% NC13
InitialRate_NC13_figure = figure;
nc = 2; % NC13
hold on
errorbar(0:0.025:1,average_fittedRate_r0(:,nc),SEM_fittedRate_r0(:,nc),'Color',ColorChoice(1,:))
% Females
errorbar(0:0.025:1,average_fittedRate_r1_female(:,nc),SEM_fittedRate_r1_female(:,nc),'Color',ColorChoice(2,:))
errorbar(0:0.025:1,average_fittedRate_r2_female(:,nc),SEM_fittedRate_r2_female(:,nc),'Color',ColorChoice(3,:))
errorbar(0:0.025:1,average_fittedRate_r3_female(:,nc),SEM_fittedRate_r3_female(:,nc),'Color',ColorChoice(4,:))
% % Males
% errorbar(0:0.025:1,average_fittedRate_r1_male(:,nc),SEM_fittedRate_r1_male(:,nc))
% errorbar(0:0.025:1,average_fittedRate_r2_male(:,nc),SEM_fittedRate_r2_male(:,nc))
% errorbar(0:0.025:1,average_fittedRate_r3_male(:,nc),SEM_fittedRate_r3_male(:,nc))

xlim([0.15 0.5])
ylim([0 400])

legend('r0','r1-female','r2-female','r3-female')%,'r1-male','r2-male','r3-male') 
xlabel('AP Position')
ylabel('Initial rate (AU/min)')
title('Initial rate of RNAP loading along AP axis, at NC 13')
StandardFigure(InitialRate_NC13_figure, InitialRate_NC13_figure.CurrentAxes)
%standardizeFigure_YJK(gca,legend)
saveas(InitialRate_NC13_figure,[FigPath 'InitialRate_AsymmetricFit_r0123_female' , '_NC13' , '.tif']); 
saveas(InitialRate_NC13_figure,[FigPath 'InitialRate_AsymmetricFit_r0123_female' , '_NC13' , '.pdf']); 

% NC14
InitialRate_NC14_figure = figure;
nc = 3; % NC13
hold on
errorbar(0:0.025:1,average_fittedRate_r0(:,nc),SEM_fittedRate_r0(:,nc),'Color',ColorChoice(1,:))
% Female
errorbar(0:0.025:1,average_fittedRate_r1_female(:,nc),SEM_fittedRate_r1_female(:,nc),'Color',ColorChoice(2,:))
errorbar(0:0.025:1,average_fittedRate_r2_female(:,nc),SEM_fittedRate_r2_female(:,nc),'Color',ColorChoice(3,:))
errorbar(0:0.025:1,average_fittedRate_r3_female(:,nc),SEM_fittedRate_r3_female(:,nc),'Color',ColorChoice(4,:))
% Male
% errorbar(0:0.025:1,average_fittedRate_r1_male(:,nc),SEM_fittedRate_r1_male(:,nc))
% errorbar(0:0.025:1,average_fittedRate_r2_male(:,nc),SEM_fittedRate_r2_male(:,nc))
% errorbar(0:0.025:1,average_fittedRate_r3_male(:,nc),SEM_fittedRate_r3_male(:,nc))

xlim([0.15 0.5])
ylim([0 400])

legend('r0','r1-female','r2-female','r3-female')%,'r1-male','r2-male','r3-male') 
xlabel('AP Position')
ylabel('Initial rate (AU/min)')
title('Initial rate of RNAP loading along AP axis, at NC 14')
StandardFigure(InitialRate_NC14_figure, InitialRate_NC14_figure.CurrentAxes)

% standardizeFigure_YJK(gca,legend)
saveas(InitialRate_NC14_figure,[FigPath 'InitialRate_AsymmetricFit_r0123_female_' , '_NC14' , '.tif']); 
saveas(InitialRate_NC14_figure,[FigPath 'InitialRate_AsymmetricFit_r0123_female_' , '_NC14' , '.pdf']); 


%% Save the fitted initial rate and SEM 

% Define the values

save('E:\YangJoon\LivemRNA\Data\Dropbox\OpposingGradient\OpposingGradients_ProcessedData\AveragedInitialRate_AsymmetricFit.mat',...
        'average_fittedRate_r0','SEM_fittedRate_r0',...
        'average_fittedRate_r1_female','SEM_fittedRate_r1_female',...
        'average_fittedRate_r2_female','SEM_fittedRate_r2_female',...
        'average_fittedRate_r3_female','SEM_fittedRate_r3_female')

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Part 2. Generating plots from saved data.
% First, load the datasets from above.
%% Load the fitted initial slope (Data)
% Data calculated from the script :
% main02_plot_Initial_Loading_Rates_Asymmetric.m
% 
InitialSlope = load([FilePath, filesep, 'AveragedInitialRate_AsymmetricFit.mat']);

%% Extract useful fields 
% Extract the initial slope from the saved structure.
nc = 14;% NC14
NC= nc - 11;
InitialRate_r0_NC14 = InitialSlope.average_fittedRate_r0(:,NC);
InitialRate_r1_NC14 = InitialSlope.average_fittedRate_r1_female(:,NC);
InitialRate_r2_NC14 = InitialSlope.average_fittedRate_r2_female(:,NC);
InitialRate_r3_NC14 = InitialSlope.average_fittedRate_r3_female(:,NC);

InitialRate_SEM_r0_NC14 = InitialSlope.SEM_fittedRate_r0(:,NC);
InitialRate_SEM_r1_NC14 = InitialSlope.SEM_fittedRate_r1_female(:,NC);
InitialRate_SEM_r2_NC14 = InitialSlope.SEM_fittedRate_r2_female(:,NC);
InitialRate_SEM_r3_NC14 = InitialSlope.SEM_fittedRate_r3_female(:,NC);

%% plot
% NC14
InitialRate_NC14_figure = figure;
nc = 3; % NC13
hold on
errorbar(0:0.025:1,InitialRate_r0_NC14,InitialRate_SEM_r0_NC14,'Color',ColorChoice(1,:))
% Female
errorbar(0:0.025:1,InitialRate_r1_NC14,InitialRate_SEM_r1_NC14,'Color',ColorChoice(2,:))
errorbar(0:0.025:1,InitialRate_r2_NC14,InitialRate_SEM_r2_NC14,'Color',ColorChoice(3,:))
errorbar(0:0.025:1,InitialRate_r3_NC14,InitialRate_SEM_r3_NC14,'Color',ColorChoice(4,:))

end