%This code is using the "mean fits" files generated by my version of FitMeanAPAsymetric 
%to plot the initial rates along APaxis. 
%The T_on (time of activation of the transcription,extrapolated from the initial rate)
%can also be plotted.

%% Load the datasets (using LoadMS2Sets.m)
% Data_r0 = LoadMS2Sets('r0')
% Data_r1_female = LoadMS2Sets('r1')
% Data_r2_female = LoadMS2Sets('r2')
% Data_r3_female = LoadMS2Sets('r3')
% Data_r3_female_prime = LoadMS2Sets('r3prime')

% Edit the LoadMS2Sets for MeanFitsV2.mate
Data_r1 = LoadMS2Sets('r1-new-female','dontCompare');
Data_r1mid = LoadMS2Sets('r1-mid','dontCompare');
Data_r1close = LoadMS2Sets('r1-close','dontCompare');
Data_r0 = LoadMS2Sets('r0-new-female','dontCompare');
Data_r2 = LoadMS2Sets('r2-new-female','dontCompare');
Data_r2close = LoadMS2Sets('r2 1+2','dontCompare');
Data_r2far = LoadMS2Sets('r2 1+3','dontCompare');



%% Extract the fitted values from all of my datasets
% Caveat : For now (7/11/2019), I'll use r0 from my old construct since I
% don't have NC14 from the new r0 construct. Thus, I'll use MeanFits.mat
% from old r0, and MeanFitsV2 (Asymmetric fit) from the new ones.

[fittedRate_r1,fittedRateSD_r1,fittedTon_r1] = Extract_Fields_MeanFitsV2(Data_r1);
[fittedRate_r1mid,fittedRateSD_r1mid,fittedTon_r1mid] = Extract_Fields_MeanFitsAsymmetric(Data_r1mid);
[fittedRate_r1close,fittedRateSD_r1close,fittedTon_r1close] = Extract_Fields_MeanFitsAsymmetric(Data_r1close);
[fittedRate_r0,fittedRateSD_r0,fittedTon_r0] = Extract_Fields_MeanFitsV2(Data_r0);
[fittedRate_r2,fittedRateSD_r2,fittedTon_r2] = Extract_Fields_MeanFitsV2(Data_r2);
[fittedRate_r2close,fittedRateSD_r2close,fittedTon_r2close] = Extract_Fields_MeanFitsAsymmetric(Data_r2close);
[fittedRate_r2far,fittedRateSD_r2far,fittedTon_r2far] = Extract_Fields_MeanFitsAsymmetric(Data_r2far);

% %% plot individual fitted curves to check
% NC = 2; %NC13
% 
% hold on
% for i=1:length(Data_r1)
%     errorbar(0:0.025:1,fittedRate_r1(:,NC,i),fittedRateSD_r1(:,NC,i))
% end
% 
% hold on
% for i=1:length(Data_r1mid)
%     errorbar(0:0.025:1,fittedRate_r1mid(:,NC,i),fittedRateSD_r1mid(:,NC,i))
%     pause
% end
% 
% hold on
% for i=1:length(Data_r1close)
%     errorbar(0:0.025:1,fittedRate_r1close(:,NC,i),fittedRateSD_r1close(:,NC,i))
%     %pause
% end

%% Calculate the average using nanmean, nanstd
average_fittedRate_r1 = nanmean(fittedRate_r1,3);
SEM_fittedRate_r1 = nanstd(fittedRate_r1,0,3)/sqrt(length(Data_r1));

average_fittedRate_r1mid = nanmean(fittedRate_r1mid,3);
SEM_fittedRate_r1mid = nanstd(fittedRate_r1mid,0,3)/sqrt(length(Data_r1mid));

average_fittedRate_r1close = nanmean(fittedRate_r1close,3);
SEM_fittedRate_r1close = nanstd(fittedRate_r1close,0,3)/sqrt(length(Data_r1close));

average_fittedRate_r0 = nanmean(fittedRate_r0,3);
SEM_fittedRate_r0 = nanstd(fittedRate_r0,0,3)/sqrt(length(Data_r0));

average_fittedRate_r2 = nanmean(fittedRate_r2,3);
SEM_fittedRate_r2 = nanstd(fittedRate_r2,0,3)/sqrt(length(Data_r2));

average_fittedRate_r2close = nanmean(fittedRate_r2close,3);
SEM_fittedRate_r2close = nanstd(fittedRate_r2close,0,3)/sqrt(length(Data_r2close));

average_fittedRate_r2far = nanmean(fittedRate_r2far,3);
SEM_fittedRate_r2far = nanstd(fittedRate_r2far,0,3)/sqrt(length(Data_r2far));

%% Color definition
% This is defining the line color
colorDict = struct();
colorDict.blue = [115,143,193]/255; %[115,143,170]/255;
colorDict.red =  [213,108,85]/255; %[200,108,85]/255;
colorDict.yellow = [234,194,100]/255;
colorDict.cyan = [108,188,233]/255;
colorDict.magenta = [208,109,171]/255;
colorDict.lightBlue = [115,142,193]/255;
colorDict.purple = [171,133,172]/255;
colorDict.green =  [122,169,116]/255; %[122,150,116]/255;
colorDict.brown = [179,155,142]/255;
colorDict.darkgreen = [126,157,144]/255;

ColorChoice = [colorDict.magenta; colorDict.lightBlue; colorDict.yellow; colorDict.red; colorDict.brown; colorDict.purple]; % 4 embryos max. it could be extended easily
%% Plot the averaged fittedRate (initial rate of RNAP loading), and SEM

FigPath = 'E:\kaitlin\LivemRNA\plots\all_r2';

% NC13
InitialRate_NC13_figure = figure;
nc = 2; % NC13
hold on
% Females
errorbar(0:0.025:1,average_fittedRate_r0(:,nc),SEM_fittedRate_r0(:,nc),'Color',ColorChoice(4,:))
errorbar(0:0.025:1,average_fittedRate_r1(:,nc),SEM_fittedRate_r1(:,nc),'Color',ColorChoice(1,:))
errorbar(0:0.025:1,average_fittedRate_r1mid(:,nc),SEM_fittedRate_r1mid(:,nc),'Color',ColorChoice(2,:))
errorbar(0:0.025:1,average_fittedRate_r1close(:,nc),SEM_fittedRate_r1close(:,nc),'Color',ColorChoice(3,:))
errorbar(0:0.025:1,average_fittedRate_r2(:,nc),SEM_fittedRate_r2(:,nc),'Color',ColorChoice(5,:))
errorbar(0:0.025:1,average_fittedRate_r2close(:,nc),SEM_fittedRate_r2close(:,nc),'Color',ColorChoice(6,:))
errorbar(0:0.025:1,average_fittedRate_r2far(:,nc),SEM_fittedRate_r2far(:,nc))

xlim([0.15 0.5])
ylim([0 400])

%legend('r0','r1','r1-mid','r1-close','r2','r3') 
legend('r0','r1','r1-mid','r1-close','r2','r2(1+2)','r2(1+3)')
xlabel('AP Position')
ylabel('Initial rate (AU/min)')
title('Initial rate of RNAP loading along AP axis, at NC 13')
StandardFigure(InitialRate_NC13_figure, InitialRate_NC13_figure.CurrentAxes)
%standardizeFigure_YJK(gca,legend)
saveas(InitialRate_NC13_figure,[FigPath 'InitialRate_AsymmetricFit_all_r2' , '_NC13' , '.tif']); 

% NC14
InitialRate_NC14_figure = figure;
nc = 3; % NC13
hold on
% Female
errorbar(0:0.025:1,average_fittedRate_r0(:,nc),SEM_fittedRate_r0(:,nc),'Color',ColorChoice(4,:))
errorbar(0:0.025:1,average_fittedRate_r1(:,nc),SEM_fittedRate_r1(:,nc),'Color',ColorChoice(1,:))
errorbar(0:0.025:1,average_fittedRate_r1mid(:,nc),SEM_fittedRate_r1mid(:,nc),'Color',ColorChoice(2,:))
errorbar(0:0.025:1,average_fittedRate_r1close(:,nc),SEM_fittedRate_r1close(:,nc),'Color',ColorChoice(3,:))
errorbar(0:0.025:1,average_fittedRate_r2(:,nc),SEM_fittedRate_r2(:,nc),'Color',ColorChoice(5,:))
errorbar(0:0.025:1,average_fittedRate_r2close(:,nc),SEM_fittedRate_r2close(:,nc),'Color',ColorChoice(6,:))
errorbar(0:0.025:1,average_fittedRate_r2far(:,nc),SEM_fittedRate_r2far(:,nc))

xlim([0.15 0.5])
ylim([0 400])

legend('r0','r1','r1-mid','r1-close','r2','r2(1+2)','r2(1+3)')
xlabel('AP Position')
ylabel('Initial rate (AU/min)')
title('Initial rate of RNAP loading along AP axis, at NC 14')
StandardFigure(InitialRate_NC14_figure, InitialRate_NC14_figure.CurrentAxes)

% standardizeFigure_YJK(gca,legend)
saveas(InitialRate_NC14_figure,[FigPath 'InitialRate_AsymmetricFit_all_r2' , '_NC14' , '.tif']); 


%% Save the fitted initial rate and SEM 

% Define the values
% 
% save('E:\kaitlin\LivemRNA\Data\DynamicsResults',...
%         'average_fittedRate_r2','SEM_fittedRate_r2',...
%         'average_fittedRate_r1mid','SEM_fittedRate_r1mid',...
%         'average_fittedRate_r1close','SEM_fittedRate_r1close')
